<?php
/**
 * @file
 * Salvattore masonry plugin for views.
 */

/**
 * Implements hook_permission().
 */
function salvattore_permission() {
  return array(
    'manage Salvattore settings' => array(
      'title' => t('Manage Salvattore settings'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function salvattore_menu() {
  $items = array();

  $items['admin/config/user-interface/salvattore'] = array(
    'title' => 'Salvattore Settings',
    'description' => 'Configure Salvattore',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('salvattore_settings_form'),
    'access arguments' => array('manage Salvattore settings'),
    'file' => 'salvattore.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_autoload_info.
 */
function salvattore_autoload_info() {
  return array(
    'views_plugin_style_salvattore' => 'views_plugin_style_salvattore.inc',
  );
}

/**
 * Implements hook_views_api()
 */
function salvattore_views_api() {
  return array(
    'api' => '3.0',
    'path' => backdrop_get_path('module', 'salvattore'),
    'template_path' => backdrop_get_path('module', 'salvattore'),
  );
}

/**
 * Preprocess function for views_view_salvattore.tpl.php.
 */
function template_preprocess_views_view_salvattore(&$vars) {
  // Run preprocess function for unformatted style
  template_preprocess_views_view_unformatted($vars);
  // Get view options
  $view = $vars['view'];
  $options = $vars['options'];
}

/**
 * Implements hook_preprocess_page().
 */
function salvattore_preprocess_page(&$variables) {
  if (config_get('salvattore.settings', 'salvattore_use_min_js')) {
    backdrop_add_js(backdrop_get_path('module', 'salvattore') . '/js/salvattore.min.js', array(
      'scope' => 'footer',
    ));
  } else {
    backdrop_add_js(backdrop_get_path('module', 'salvattore') . '/js/salvattore.js', array(
      'scope' => 'footer',
    ));
  }

  if (config_get('salvattore.settings', 'salvattore_load_default_css')) {
    backdrop_add_css(backdrop_get_path('module', 'salvattore') . '/css/salvattore_default.css', array(
      'type' => 'file',
      'preprocess' => FALSE, // see README
    ));
  }
}
